spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch1
    username: root
    password: 123456
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  batch:
    initialize-schema: always
  redis:
    host: 10.55.1.133
    port: 6379

  #batch:
    #job:
     # names: parentJob
    #schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  #batch:
    #initializer:
      #enabled: true